### ISSUE TITLE
Meili on Android

### ISSUE THREAD

**Issue by soheilarmin** [valhalla/meili#63]
I could successfully build baldr, meili, midgard, sif as dependencies to build THOR for Android Armv7. Now I can create the MapMatcher with MapMatcherFactory, to match origin and destination points. Passing points to the GetBestPath of PathAlgorithm is ok and I get correct routes. Everything is fine except the MapMatcher::OfflineMatch(...) is taking a long time to process. For the first Measurement it will lead to call IndexTile(...) which is implemented in candidate_search.cc. Is it really needed to index and cache the whole tile at once? I assume that Valhalla is designed as a server side service in mind but in blogs I read something like it can run on memory constrained mobile devices as well. Any helps to make MapMatcher::OfflineMatch faster is appreciated.

I also tried to change tile dimension of level 2 from 0.25 to 0.0625 in TileHierarchy::levels_ of baldr to get smaller tiles at this level but mjolnir will not build tiles. Seems that there is some hard coding there.

**Comment by kevinkreiser** [comment]
yes you're correct. quite a while ago we experimented with different tile sizes and found .25 to be the best solution. as it seemed we werent going to change that we pretty much stuck to it. i was hoping it wasnt hardcoded but there is a lot of code and a lot of authors...

as for the caching yes, we are aware that it is a problem. there are two things to do to meili to make the caching faster that we havent yet implemented.

* use the online shape decoder to avoid allocations. this cut shape access timing significantly in loki and would be useful here as well
* re bin the tiles on a per bin basis. every tile stores the edges that intersect it in an index, each cell of the tiles index is appx 1/25th (its a 5x5 grid of the tile) of the original tiles size. So instead of binning on the tile we should rebin on the bins of the tile. this would reduce the amount of a tile that would be loaded for any one point (it would make subsequent calls more likely to get a cache  miss though).

we dont currently have the time to spend on these but both are pretty low effort. feel free to take a stab!
